# Generated by Django 3.2.4 on 2021-07-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='replies',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
