# Generated by Django 3.2.4 on 2021-07-07 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_topic_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='replies',
        ),
    ]
